project:
  type: book
  output-dir: docs

execute:
  freeze: false

book:
  title: "Building Community-Engaged Statistics and Data Science (CESDS) Courses"
  site-url: https://community-engaged-stats-ds.github.io/CESDS_handbook/
  repo-url: https://github.com/Community-Engaged-Stats-DS/CESDS_handbook
  author: "Ming An, Laurie Baker, Karen Benway, Stacy DeRuiter, Tyler George, Claire Kelling, Gretchen Martinet, Emily Robinson, and Rori Rohlfs"
  
  date: today
  date-format: "[Last updated on] MMMM D, YYYY"

  sidebar:
    collapse-level: 2
    
  chapters:
    - index.qmd
    - part: "DEVELOPMENT"
      chapters:
        - 1-course-design.qmd
        - 2-scoping-projects.qmd
        - 3-community-partnerships.qmd

    - part: "IMPLEMENTATION"
      chapters:
        - 4-student-project-work.qmd
        - 5-ethics-community-engagement.qmd
        - 6-common-challenges.qmd
        - 7-wrap-up.qmd

    - references.qmd

  page-footer:
    border: true
    left: "This work is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
    right: "[CESDS Website](https://community-engaged-stats-ds.github.io/CESDS_website/)"

  search:
    location: navbar
    type: overlay
    copy-button: true

bibliography: references.bib

format:
  html:
    theme: [zephyr]
    page-layout: full
    toc: true
    toc-depth: 3

  pdf:
    documentclass: scrreprt
